/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StudentActivityPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MODEL_OPTIONS = {
  openai: [
    // GPT-5 Series (Reasoning Models)
    { id: "gpt-5", name: "GPT-5 (Reasoning)" },
    { id: "gpt-5-mini", name: "GPT-5 Mini (Reasoning)" },
    { id: "gpt-5-nano", name: "GPT-5 Nano (Reasoning)" },
    // GPT-4o Series
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    // GPT-4 Series
    { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
    { id: "gpt-4", name: "GPT-4" },
    // Legacy
    { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo" }
  ],
  claude: [
    // Claude 4.x Series (Latest)
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4.5 (Recommended)" },
    { id: "claude-opus-4-1-20250805", name: "Claude Opus 4.1" },
    { id: "claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5" },
    // Claude 3.7 Series
    { id: "claude-3-7-sonnet-20250219", name: "Claude 3.7 Sonnet" },
    // Claude 3.5 Series
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet" },
    { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku (Fastest)" },
    // Claude 3 Series (Legacy)
    { id: "claude-3-opus-20240229", name: "Claude 3 Opus" },
    { id: "claude-3-haiku-20240307", name: "Claude 3 Haiku" }
  ],
  gemini: [
    // Gemini 2.5 Series (Latest)
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash (Stable)" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    // Gemini 2.0 Series
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    { id: "gemini-2.0-flash-preview-image-generation", name: "Gemini 2.0 Flash (Image Gen)" },
    // Gemini 1.5 Series
    { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro" },
    { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash" },
    { id: "gemini-1.5-flash-8b", name: "Gemini 1.5 Flash 8B" }
  ],
  grok: [
    // Grok 4.x Series (Latest)
    { id: "grok-4-0709", name: "Grok 4" },
    { id: "grok-4-1-fast", name: "Grok 4.1 Fast (Recommended)" },
    { id: "grok-4-1-fast-non-reasoning", name: "Grok 4.1 Fast (Non-Reasoning)" },
    // Grok 3 Series
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-3-mini", name: "Grok 3 Mini" },
    // Grok Code
    { id: "grok-code-fast-1", name: "Grok Code Fast" },
    // Grok 2 Series (Legacy)
    { id: "grok-2-vision-1212", name: "Grok 2 Vision" },
    { id: "grok-2-image-1212", name: "Grok 2 Image" }
  ]
};
var DEFAULT_MODELS = {
  openai: "gpt-4o-mini",
  claude: "claude-sonnet-4-5-20250929",
  gemini: "gemini-2.5-flash",
  grok: "grok-4-1-fast"
};
var DEFAULT_SETTINGS = {
  apiProvider: "openai",
  apiKey: "",
  targetCharCount: 500,
  outputFolder: "",
  modelId: "gpt-4o-mini"
};
function countChars(text) {
  return text.length;
}
function countBytes(text) {
  let bytes = 0;
  for (let i = 0; i < text.length; i++) {
    const char = text.charAt(i);
    if (char === "\n") {
      bytes += 1;
    } else if (escape(char).length > 4) {
      bytes += 3;
    } else {
      bytes += 1;
    }
  }
  return bytes;
}
function estimateBytes(charCount) {
  return Math.round(charCount * 0.8 * 3 + charCount * 0.2 * 1);
}
function parseTSV(data) {
  const lines = data.trim().split("\n");
  const activities = [];
  for (const line of lines) {
    const parts = line.split("	");
    if (parts.length >= 3) {
      activities.push({
        studentId: parts[0].trim(),
        studentName: parts[1].trim(),
        activityContent: parts.slice(2).join(" ").trim()
      });
    }
  }
  return activities;
}
function generateMarkdownTable(records) {
  let table = "| 학번 | 성명 | 학생활동기록 | 교사관찰기록 | 글자 수 | 바이트 수 |\n";
  table += "|------|------|-------------|-------------|---------|----------|\n";
  for (const record of records) {
    const escapedActivity = record.activityContent.replace(/\|/g, "\\|").replace(/\n/g, " ");
    const escapedObservation = record.observation.replace(/\|/g, "\\|").replace(/\n/g, " ");
    table += `| ${record.studentId} | ${record.studentName} | ${escapedActivity} | ${escapedObservation} | ${record.charCount} | ${record.byteCount} |\n`;
  }
  return table;
}
function generateTSVData(records) {
  let tsv = "학번\t성명\t학생활동기록\t교사관찰기록\t글자 수\t바이트 수\n";
  for (const record of records) {
    const cleanActivity = record.activityContent.replace(/[\t\n\r]/g, " ");
    const cleanObservation = record.observation.replace(/[\t\n\r]/g, " ");
    tsv += `${record.studentId}\t${record.studentName}\t${cleanActivity}\t${cleanObservation}\t${record.charCount}\t${record.byteCount}\n`;
  }
  return tsv;
}
var SYSTEM_PROMPT = `당신은 학생을 깊이 이해하고 애정을 가지고 관찰하는 한국 고등학교 담임교사입니다.
학생의 활동 내용을 바탕으로 교사 관찰 기록을 작성해주세요.

[핵심 원칙]
- 인공지능이 작성한 것이 아닌, 교사가 학생을 직접 관찰하고 애정을 담아 작성한 기록처럼 보여야 합니다
- 학생의 강점, 노력, 성장 과정을 따뜻하게 서술합니다
- 객관적 사실에 기반하되, 교사의 긍정적 관점을 담습니다

[문체 규칙]
- 서술형 종결어미 사용: "~함", "~임", "~남", "~보임", "~드러냄"
- 제목, 머리말, 학생 이름 포함 금지
- 3인칭 관찰자 시점으로 작성
- 한 문단으로 자연스럽게 이어지도록 작성

[내용 구성]
1. 활동의 구체적 맥락과 참여 양상
2. 학생이 보여준 역량이나 태도
3. 활동을 통한 성장이나 발전 가능성

[피해야 할 표현]
- AI, VR, AR 등 영문 약어 → 인공지능, 가상현실, 증강현실 사용
- 과도한 수식어나 빈 칭찬
- 모든 학생에게 적용 가능한 일반적인 표현
- 기계적이거나 정형화된 문장 패턴

[좋은 예시 표현]
- "탐구 과정에서 꼼꼼한 자료 조사와 논리적 분석력을 보여줌"
- "모둠 활동 시 다양한 의견을 존중하며 협력적 태도로 참여함"
- "스스로 문제를 발견하고 해결책을 모색하는 자기주도적 학습 역량을 갖춤"

[출력 형식]
- 추가 설명이나 머리말 없이 교사관찰기록 본문만 출력
- 자연스러운 한 문단으로 구성`;
async function callOpenAI(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `[제약 조건]
- 목표 글자 수: ${targetCharCount}자 (±10%)

[입력]
학번: ${activity.studentId}
이름: ${activity.studentName}
활동내용: ${activity.activityContent}

[출력]
교사관찰기록만 출력 (추가 설명 없이)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.openai.com/v1/chat/completions",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: modelId,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userPrompt }
      ],
      max_tokens: 2e3,
      temperature: 0.7
    })
  });
  if (response.status !== 200) {
    throw new Error(`OpenAI API 오류: ${response.status}`);
  }
  return response.json.choices[0].message.content.trim();
}
async function callClaude(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `[제약 조건]
- 목표 글자 수: ${targetCharCount}자 (±10%)

[입력]
학번: ${activity.studentId}
이름: ${activity.studentName}
활동내용: ${activity.activityContent}

[출력]
교사관찰기록만 출력 (추가 설명 없이)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: modelId || "claude-3-5-sonnet-20241022",
      max_tokens: 2e3,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userPrompt }]
    })
  });
  if (response.status !== 200) {
    throw new Error(`Claude API 오류: ${response.status}`);
  }
  return response.json.content[0].text.trim();
}
async function callGemini(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `${SYSTEM_PROMPT}

[제약 조건]
- 목표 글자 수: ${targetCharCount}자 (±10%)

[입력]
학번: ${activity.studentId}
이름: ${activity.studentName}
활동내용: ${activity.activityContent}

[출력]
교사관찰기록만 출력 (추가 설명 없이)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: `https://generativelanguage.googleapis.com/v1beta/models/${modelId || "gemini-1.5-flash"}:generateContent?key=${apiKey}`,
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: userPrompt }]
        }
      ],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 2e3
      }
    })
  });
  if (response.status !== 200) {
    throw new Error(`Gemini API 오류: ${response.status}`);
  }
  return response.json.candidates[0].content.parts[0].text.trim();
}
async function callGrok(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `[제약 조건]
- 목표 글자 수: ${targetCharCount}자 (±10%)

[입력]
학번: ${activity.studentId}
이름: ${activity.studentName}
활동내용: ${activity.activityContent}

[출력]
교사관찰기록만 출력 (추가 설명 없이)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.x.ai/v1/chat/completions",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: modelId || "grok-3-fast",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userPrompt }
      ],
      max_tokens: 2e3,
      temperature: 0.7
    })
  });
  if (response.status !== 200) {
    throw new Error(`Grok API 오류: ${response.status}`);
  }
  return response.json.choices[0].message.content.trim();
}
var InputModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.inputData = "";
    this.plugin = plugin;
    this.targetCharCount = plugin.settings.targetCharCount;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("student-activity-modal");
    contentEl.createEl("h2", { text: "학생활동 → 교사관찰기록 변환" });
    contentEl.createEl("p", {
      text: "구글 스프레드시트에서 복사한 데이터를 붙여넣으세요. (학번 탭 이름 탭 활동내용)",
      cls: "student-activity-description"
    });
    const textAreaContainer = contentEl.createDiv({ cls: "student-activity-textarea-container" });
    const textArea = textAreaContainer.createEl("textarea", {
      cls: "student-activity-textarea",
      attr: { rows: "10", placeholder: "10101	김철수	프로젝트 활동에서 리더 역할을 맡아...\n10102	이영희	토론 수업에서 적극적으로 참여하여..." }
    });
    textArea.addEventListener("input", (e) => {
      this.inputData = e.target.value;
      this.updatePreview();
    });
    const previewContainer = contentEl.createDiv({ cls: "student-activity-preview" });
    previewContainer.createEl("h4", { text: "입력 데이터 미리보기" });
    const previewContent = previewContainer.createDiv({ cls: "student-activity-preview-content" });
    previewContent.setText("데이터를 입력하면 여기에 미리보기가 표시됩니다.");
    const charCountContainer = contentEl.createDiv({ cls: "student-activity-char-count" });
    new import_obsidian.Setting(charCountContainer).setName("목표 글자 수").setDesc("생성될 교사관찰기록의 목표 글자 수를 설정합니다.").addText((text) => {
      text.setValue(String(this.targetCharCount)).onChange((value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.targetCharCount = num;
          this.updateByteEstimate();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.min = "100";
      text.inputEl.max = "2000";
    });
    const byteEstimateEl = charCountContainer.createDiv({ cls: "student-activity-byte-estimate" });
    byteEstimateEl.setText(`예상 바이트 수: ${estimateBytes(this.targetCharCount)} 바이트`);
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "취소",
      cls: "student-activity-cancel-btn"
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
    const submitBtn = buttonContainer.createEl("button", {
      text: "교사관찰기록 생성",
      cls: "mod-cta student-activity-submit-btn"
    });
    submitBtn.addEventListener("click", () => {
      if (!this.inputData.trim()) {
        new import_obsidian.Notice("데이터를 입력해주세요.");
        return;
      }
      const activities = parseTSV(this.inputData);
      if (activities.length === 0) {
        new import_obsidian.Notice("유효한 데이터가 없습니다. 형식: 학번 [탭] 이름 [탭] 활동내용");
        return;
      }
      this.onSubmit(this.inputData, this.targetCharCount);
      this.close();
    });
  }
  updatePreview() {
    const previewContent = this.contentEl.querySelector(".student-activity-preview-content");
    if (!previewContent)
      return;
    const activities = parseTSV(this.inputData);
    if (activities.length === 0) {
      previewContent.setText("유효한 데이터가 없습니다. 형식: 학번 탭 이름 탭 활동내용");
      return;
    }
    let preview = `총 ${activities.length}명의 학생 데이터:\n\n`;
    for (const activity of activities.slice(0, 5)) {
      preview += `- ${activity.studentId} ${activity.studentName}: ${activity.activityContent.substring(0, 50)}...\n`;
    }
    if (activities.length > 5) {
      preview += `\n... 외 ${activities.length - 5}명`;
    }
    previewContent.setText(preview);
  }
  updateByteEstimate() {
    const byteEstimateEl = this.contentEl.querySelector(".student-activity-byte-estimate");
    if (byteEstimateEl) {
      byteEstimateEl.setText(`예상 바이트 수: ${estimateBytes(this.targetCharCount)} 바이트`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ProgressModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
    this.progressText = null;
    this.progressBar = null;
    this.progressPercentText = null;
    this.statusText = null;
    this.currentIndex = 0;
    this.totalCount = 0;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("student-activity-progress-modal");
    contentEl.createEl("h2", { text: "교사관찰기록 생성 중" });
    this.progressText = contentEl.createEl("p", { cls: "progress-text" });
    this.progressText.setText("AI 변환 준비 중...");
    const progressWrapper = contentEl.createDiv({ cls: "progress-wrapper" });
    const progressBarContainer = progressWrapper.createDiv({ cls: "progress-bar-container" });
    this.progressBar = progressBarContainer.createDiv({ cls: "progress-bar" });
    this.progressBar.style.width = "0%";
    this.progressPercentText = progressWrapper.createDiv({ cls: "progress-percent" });
    this.progressPercentText.setText("0%");
    this.statusText = contentEl.createEl("p", { cls: "progress-status" });
    this.statusText.setText("잠시만 기다려주세요...");
    const infoText = contentEl.createEl("p", { cls: "progress-info" });
    infoText.setText("AI가 학생활동 내용을 교사관찰기록 문체로 변환하고 있습니다.");
  }
  updateProgress(current, total, studentName) {
    this.currentIndex = current;
    this.totalCount = total;
    const percentage = Math.round(current / total * 100);
    if (this.progressText) {
      this.progressText.setText(`${current} / ${total}명 - "${studentName}" 변환 중...`);
    }
    if (this.progressBar) {
      this.progressBar.style.width = `${percentage}%`;
    }
    if (this.progressPercentText) {
      this.progressPercentText.setText(`${percentage}%`);
    }
    if (this.statusText) {
      if (current === total) {
        this.statusText.setText("변환 완료! 결과를 저장하고 있습니다...");
      } else {
        this.statusText.setText(`남은 학생: ${total - current}명`);
      }
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var StudentActivitySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.modelDropdown = null;
    this.plugin = plugin;
  }
  getProviderName(provider) {
    const names = {
      openai: "OpenAI",
      claude: "Anthropic",
      gemini: "Google",
      grok: "xAI"
    };
    return names[provider] || provider;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "학생활동 → 교사관찰기록 변환 설정" });
    new import_obsidian.Setting(containerEl).setName("AI 제공자").setDesc("사용할 AI API 제공자를 선택합니다.").addDropdown((dropdown) => {
      dropdown.addOption("openai", "OpenAI (GPT)");
      dropdown.addOption("claude", "Anthropic (Claude)");
      dropdown.addOption("gemini", "Google (Gemini)");
      dropdown.addOption("grok", "xAI (Grok)");
      dropdown.setValue(this.plugin.settings.apiProvider);
      dropdown.onChange(async (value) => {
        this.plugin.settings.apiProvider = value;
        this.plugin.settings.modelId = DEFAULT_MODELS[value];
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const apiKeyPlaceholders = {
      openai: "sk-...",
      claude: "sk-ant-...",
      gemini: "AIza...",
      grok: "xai-..."
    };
    new import_obsidian.Setting(containerEl).setName("API 키").setDesc(`${this.getProviderName(this.plugin.settings.apiProvider)} API 키를 입력합니다.`).addText(
      (text) => text.setPlaceholder(apiKeyPlaceholders[this.plugin.settings.apiProvider] || "API 키").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    const currentProvider = this.plugin.settings.apiProvider;
    const models = MODEL_OPTIONS[currentProvider] || [];
    new import_obsidian.Setting(containerEl).setName("모델").setDesc(`${this.getProviderName(currentProvider)}에서 사용할 AI 모델을 선택합니다.`).addDropdown((dropdown) => {
      this.modelDropdown = dropdown;
      for (const model of models) {
        dropdown.addOption(model.id, model.name);
      }
      const modelExists = models.some((m) => m.id === this.plugin.settings.modelId);
      if (modelExists) {
        dropdown.setValue(this.plugin.settings.modelId);
      } else {
        dropdown.setValue(DEFAULT_MODELS[currentProvider]);
        this.plugin.settings.modelId = DEFAULT_MODELS[currentProvider];
        this.plugin.saveSettings();
      }
      dropdown.onChange(async (value) => {
        this.plugin.settings.modelId = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("기본 목표 글자 수").setDesc("교사관찰기록의 기본 목표 글자 수를 설정합니다.").addText((text) => {
      text.setPlaceholder("500").setValue(String(this.plugin.settings.targetCharCount)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.targetCharCount = num;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
    });
    new import_obsidian.Setting(containerEl).setName("결과 저장 폴더").setDesc("변환 결과를 저장할 폴더 경로 (비워두면 Vault 루트에 저장)").addText(
      (text) => text.setPlaceholder("교사관찰기록").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "NEIS 글자수/바이트수 계산 기준" });
    const infoDiv = containerEl.createDiv({ cls: "student-activity-info" });
    infoDiv.innerHTML = `
      <ul>
        <li><strong>글자 수</strong>: 모든 문자를 1개로 계산 (한글, 영문, 숫자, 공백, 특수문자)</li>
        <li><strong>바이트 수</strong>:
          <ul>
            <li>한글, 한자: 3바이트</li>
            <li>영문, 숫자, 특수문자, 공백, 줄바꿈: 1바이트</li>
          </ul>
        </li>
      </ul>
    `;
  }
};
var StudentActivityPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Student Activity to Observation Plugin");
    await this.loadSettings();
    this.addSettingTab(new StudentActivitySettingTab(this.app, this));
    this.addCommand({
      id: "open-conversion-modal",
      name: "학생활동 → 교사관찰기록 변환 (Modal)",
      callback: () => {
        this.openConversionModal();
      }
    });
    this.addCommand({
      id: "convert-from-selection",
      name: "선택 영역에서 교사관찰기록 변환",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection();
        if (!selection.trim()) {
          new import_obsidian.Notice("텍스트를 선택해주세요.");
          return;
        }
        this.processConversion(selection, this.settings.targetCharCount);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle("학생활동 → 교사관찰기록 변환").setIcon("file-text").onClick(() => {
            this.openConversionModal();
          });
        });
      })
    );
  }
  async onunload() {
    console.log("Unloading Student Activity to Observation Plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openConversionModal() {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("API 키를 설정해주세요. (설정 → 학생활동 → 교사관찰기록 변환)");
      return;
    }
    new InputModal(this.app, this, (data, charCount) => {
      this.processConversion(data, charCount);
    }).open();
  }
  async processConversion(data, targetCharCount) {
    const activities = parseTSV(data);
    if (activities.length === 0) {
      new import_obsidian.Notice("변환할 데이터가 없습니다.");
      return;
    }
    const progressModal = new ProgressModal(this.app);
    progressModal.open();
    const records = [];
    let errorCount = 0;
    for (let i = 0; i < activities.length; i++) {
      const activity = activities[i];
      progressModal.updateProgress(i + 1, activities.length, activity.studentName);
      try {
        let observation;
        switch (this.settings.apiProvider) {
          case "openai":
            observation = await callOpenAI(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.openai,
              activity,
              targetCharCount
            );
            break;
          case "claude":
            observation = await callClaude(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.claude,
              activity,
              targetCharCount
            );
            break;
          case "gemini":
            observation = await callGemini(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.gemini,
              activity,
              targetCharCount
            );
            break;
          case "grok":
            observation = await callGrok(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.grok,
              activity,
              targetCharCount
            );
            break;
          default:
            throw new Error(`지원하지 않는 AI 제공자: ${this.settings.apiProvider}`);
        }
        records.push({
          studentId: activity.studentId,
          studentName: activity.studentName,
          activityContent: activity.activityContent,
          observation,
          charCount: countChars(observation),
          byteCount: countBytes(observation)
        });
      } catch (error) {
        console.error(`Error processing ${activity.studentName}:`, error);
        errorCount++;
        records.push({
          studentId: activity.studentId,
          studentName: activity.studentName,
          activityContent: activity.activityContent,
          observation: `[변환 실패: ${error instanceof Error ? error.message : "알 수 없는 오류"}]`,
          charCount: 0,
          byteCount: 0
        });
      }
      if (i < activities.length - 1) {
        await new Promise((resolve) => setTimeout(resolve, 500));
      }
    }
    progressModal.close();
    await this.createResultNote(records);
    if (errorCount > 0) {
      new import_obsidian.Notice(`변환 완료! (${records.length - errorCount}명 성공, ${errorCount}명 실패)`);
    } else {
      new import_obsidian.Notice(`${records.length}명의 교사관찰기록 변환 완료!`);
    }
  }
  async createResultNote(records) {
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const timeStr = now.toTimeString().slice(0, 5).replace(":", "");
    const fileName = `교사관찰기록_${dateStr}_${timeStr}.md`;
    let filePath = fileName;
    if (this.settings.outputFolder) {
      const folder = this.app.vault.getAbstractFileByPath(this.settings.outputFolder);
      if (!folder) {
        await this.app.vault.createFolder(this.settings.outputFolder);
      }
      filePath = `${this.settings.outputFolder}/${fileName}`;
    }
    const content = `# 교사관찰기록 변환 결과

생성일시: ${now.toLocaleString("ko-KR")}
총 인원: ${records.length}명

## 📋 구글 스프레드시트용 복사 영역

> 아래 코드 블록을 클릭하여 전체 선택 후 복사(Ctrl+C)하세요.
> 구글 스프레드시트에 붙여넣기(Ctrl+V)하면 열이 자동으로 구분됩니다.

\`\`\`tsv
${generateTSVData(records)}\`\`\`

---

## 결과 테이블

${generateMarkdownTable(records)}

## 통계

| 항목 | 값 |
|------|-----|
| 총 인원 | ${records.length}명 |
| 평균 글자 수 | ${Math.round(records.reduce((sum, r) => sum + r.charCount, 0) / records.length)}자 |
| 평균 바이트 수 | ${Math.round(records.reduce((sum, r) => sum + r.byteCount, 0) / records.length)} 바이트 |
`;
    const file = await this.app.vault.create(filePath, content);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
  }
};
